// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "UrDigiDiet",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "UrDigiDiet",
            targets: ["AppModule"],
            bundleIdentifier: "com.ansonliu.UrDigiDiet",
            teamIdentifier: "FPQU3M2V6Z",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections(),
                .camera(purposeString: "此 App 需要使用相機拍攝飲食照片")
            ],
            appCategory: "public.app-category.food-and-drink"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)